### ISSUE TITLE
JS HACK SnippetEditor not working properly in Q4 2016

### ISSUE THREAD

**Issue by bnaragani** [AllTheDucks/jshack-v1#1] opened 2017-02-21 23:48 UTC
Hi,

When we try to edit the Hack from snippet, the editor cursor behaves incorrectly.  Start editing a line from snippet, the cursor adds/deletes the letters from different position, other than the actual cursor position. 

It might be due to the new theme implemented in BB.Ace editor had this problem when the font of the editor changes to non mono-space.

Thanks,
Bhavani.

**Comment by ralphbebendorf** [comment] 2017-02-27 02:03
This same issue appears in Q2 2016 CU3.  I have discovered that it is caused by Blackboard Inc having a universal css selector in theme_specific.css (in the new theme).
* {
    font-family: "Open Sans", sans-serif;
    text-shadow: none !important;
    letter-spacing: normal !important;
}

Using it in this way can cause:
(1) Client performance issues, as it applies the chosen style properties to all elements of any type.
(2) Can cause issues with the normal CSS inheritance cascade ie. can interfere with the normal paths of css inheritance.

I don't know why Blackboard have done this.  It is not present in earlier versions of the Blackboard theme.  The font-family css properties are covered quite adequately elsewhere eg. html selector etc..  It appears to be causing the required mono spaced fonts defined by the JS Hack building block to be overridden.

The solution is to remove the above completely and JS Hack editor should work properly again.

Cheers

Ralph Bebendorf
Queensland University of Technology

**Comment by shaneargo** [comment] 2017-03-07 03:12
Thanks for the report @bnaragani  and the extra info @rvbvstaudio.

I'm having trouble replicating the issue. Are either of you able to provide a little more detail about which versions of Bb you are using, and what theme you have selected? 

@rvbvstaudio, did this only appear upon applying CU3 or was it present in CU2 as well.

**Comment by bnaragani** [comment] 2017-03-07 03:57
Hi Shane, 
I observed the issue in BB Q2 2016 CU1. Blackboard provided new Learn 2016 theme with this release.  The theme is closer to the Blackboard ultra look. 
If we enable the Learn 2016 theme, then the Theme css is breaking the ACE editor.

Since our institution is using the Lear 2016 theme, i changed the ACE editor with Code Mirror. 

I tried to manipulate the CSS on JS Hack Page to use other fonts with mono-space, but the theme forces the font-family setting. So, i just replaced the ACE editor with CodeMirror.

Cheers,
Bhavani.

**Comment by shaneargo** [comment] 2017-03-07 04:04
Thanks @bnaragani,

I've found a work-around. I'll be publishing a new version soon.

Cheers,
Shane.

**Comment by bnaragani** [comment] 2017-03-07 04:11
Thanks Shane.

**Comment by ralphbebendorf** [comment] 2017-03-07 04:14
Hi Shane,
The problem (for us) was evident with both CU2 and CU3.

Cheers

Ralph

**Comment by ralphbebendorf** [comment] 2017-03-07 04:16
I forgot to add, that the theme used was the Bb2016 default theme

**Comment by shaneargo** [comment] 2017-03-07 04:42
Fixed in v1.0.9.

**Closed as completed by shaneargo** 2017-03-07 04:42 UTC
